config/routes.rb
Rails.application.routes.draw do
  # get 'presentation_slots/index'
  # get 'presentation_params/index'
  get 'users/index'
  devise_for :users, :skip => [:registrations], :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' },
             path: '', path_names: { sign_in: 'login', sign_up: 'signup', sign_out: 'logout' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "articles#index"
  root to: "home#index"

  get "/announcements", to: "announcements#index"
  get "/announcements/new", to: "announcements#new"
  # These routes goes last whenever possible to avoid `new` controllers getting override.
  get "/announcements/:announcement_id", to: "announcements#show"
  get "/announcements/:announcement_id/edit", to: "announcements#edit"

  get "/projects", to: "projects#index"
  get "/projects/new", to: "projects#new"
  get "/projects/:project_id", to: "projects#show"
  get "/projects/:project_id/edit", to: "projects#edit"
  get "/projects/:project_id/edit_review", to: "projects#edit_review", as: :edit_review
  get "/projects/:project_id/edit_personnel", to: "projects#edit_personnel", as: :edit_personnel
  get "/projects/:project_id/edit_details", to: "projects#edit_details", as: :edit_details
  get "/projects/:project_id/edit_industry_collab", to: "projects#edit_industry_collab", as: :edit_industry_collab

  get "/usermgmt", to: "users#index"
  get "/usermgmt/:user_id", to: "users#show"
  get "/usermgmt/:user_id/edit", to: "users#edit"
  get "/usermgmt/:user_id/edit_stud_spec_batch", to: "users#edit_stud_spec_batch", as: :edit_stud_spec_batch
  get "/usermgmt/:user_id/edit_stud_status", to: "users#edit_stud_status", as: :edit_stud_status
  get "/usermgmt/:user_id/edit_moderator_assign", to: "users#edit_moderator_assign", as: :edit_moderator_assign
  get "/usermgmt/:user_id/edit_supervisor_assign", to: "users#edit_supervisor_assign", as: :edit_supervisor_assign
  get "/usermgmt/:user_id/edit_user_role_status", to: "users#edit_user_role_status", as: :edit_user_role_status

  get "/batchmgmt", to: "batches#index"
  get "/batchmgmt/new", to: "batches#new"
  get "/batchmgmt/:batch_id", to: "batches#show"
  get "/batchmgmt/:batch_id/edit", to: "batches#edit"

  get "/presentations", to: "presentation_slots#index"

  get "/presparams", to: "presentation_params#index"
  get "/presparams/new", to: "presentation_params#new"
  get "/presparams/:params_id", to: "presentation_params#show"
  get "/presparams/:params_id/edit", to: "presentation_params#edit"

  get "/presslots", to: "presentation_slots#index"
  get "/presslots/new", to: "presentation_slots#new"
  get "/presslots/:presentation_id", to: "presentation_slots#show"
  get "/presslots/:presentation_id/edit", to: "presentation_slots#edit"

  get "/projplacements/:placement_id/edit", to: "project_placements#edit"

  get "/stats", to: "stats#index"

  resources :announcements, param: :announcement_id
  resources :projects, param: :project_id
  resources :users, param: :user_id
  resources :batches, param: :batch_id
  resources :presentation_params, param: :param_id
  resources :presentation_slots, param: :presentation_id
  resources :project_placements, param: :placement_id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable

  scope :list_student, ->{ where(user_role: "Student") }
  scope :list_coordinator, -> { where(user_role: "Coordinator") }
  scope :list_manager, -> { where(user_role: "Manager") }
  scope :list_supervisor, -> { where(is_supervisor: "Y") }
  scope :list_moderator, -> { where(user_role: "Moderator") }

  validates :user_id, length: { minimum: 6, maximum: 10 }, presence: true, uniqueness: true
  validates :user_name, length: { minimum: 2, maximum: 50 }, presence: true
  validates :user_gov_id, length: { minimum: 2, maximum: 20 }, presence: true, uniqueness: true
  validates :user_contact_no, length: { minimum: 9, maximum: 20 }, numericality: { only_integer: true }, presence: true
  validates :email, length: { minimum: 5, maximum: 128}, presence: true, uniqueness: true
  validates :is_supervisor, length: { maximum: 1 }

  has_many :announcements
  has_many :projects, class_name: "Project", foreign_key: :supervisor_id

  has_one :project_placement
  accepts_nested_attributes_for :project_placement
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:user_name, :user_gov_id, :user_gender, :user_role,
                                             :user_contact_no,:user_status, :email, :user_id]
    )
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    curr_usr_role = current_user.user_role    # The role of current user.

    if curr_usr_role == "Manager" || curr_usr_role == "Coordinator"
      @users = User.all

      @user_student = User.list_student
      @user_supervisor = User.list_supervisor
      @user_moderator = User.list_moderator

      # # Temporary
      # @users_student = User.where(user_role: "Student")
      # @users_supervisor = User.where(user_role: "Supervisor")
      # @users_moderator = User.where(user_role: "Moderator")

      if params[:search_keyword] && params[:search_keyword] != ""
        # @users = @users.where("user_id like ?", params[:search_by_id])

        # `ilike` is case-insensitive
        @users = @users.where('user_id ilike :search OR user_name ilike :search', search: "%#{params[:search_keyword]}%")
      end

    end
  end

  def show
    curr_usr_role = current_user.user_role    # The role of current user.

    if curr_usr_role == "Manager" || curr_usr_role == "Coordinator"
      @user = User.find(params[:user_id])

      if @user.batch_id.nil? || @user.batch_id == "-"
        @batch_name = "-"
        @batch_status = "-"
      else
        @batch_name = Batch.find(@user.batch_id).batch_name
        @batch_status = Batch.find(@user.batch_id).batch_status
      end

      if @user.is_supervisor == "Y"
        @user_is_supervisor = "Supervisor"
      else
        @user_is_supervisor = "-"
      end

      @user_user_remarks = check_empty_value(@user.user_remarks)
    end
  end

  def edit
    @user = User.find(params[:user_id])
  end

  def edit_stud_spec_batch
    @user = User.find(params[:user_id])
  end

  def edit_stud_status
    @user = User.find(params[:user_id])
  end

  def edit_moderator_assign
    @user = User.find(params[:user_id])
  end

  def edit_supervisor_assign
    @user = User.find(params[:user_id])
  end

  def edit_user_role_status
    @user = User.find(params[:user_id])
  end

  def update
    @user = User.find(params[:user_id])

    if @user.update(user_params)
      redirect_to @user
    else
      @user.errors.each {|err| puts err }
      puts "[DEBUG] Error is #{@user.errors.full_messages}"
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def check_empty_value(target)
    if target == "" || target.nil? || target == "-"
      "-"
    else
      target
    end
  end

  private
  def user_params
    params.require(:user).permit(
      :email, :user_name, :user_gov_id, :user_gender, :user_role, :user_contact_no, :user_status,
      :student_batch, :student_specialisation, :student_status, :project_progress_id, :batch_id, :user_remarks,
      :user_role_original, :is_supervisor
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def student_status_options
    %w[Open Ongoing Completed Terminated Other]
  end

  def user_status_options
    %w[Pending Active Inactive]
  end

  def assign_moderator_options
    # am = User.where(:user_role => %w[Coordinator Manager Moderator Supervisor]).pluck(:user_name, :user_id).append(["Moderator"])
    original_role = User.where()
    am = [original_role.user_role]
    return am
  end

  def user_role_options
    %w[Undefined Student Moderator Coordinator Manager Lecturer]
  end
end

app/views/users/_user-details-summary.html.erb
<table class="table table-borderless table-sm">
  <tr class="table-no-l-pad">
    <th class="col-2 table-no-l-pad">User ID</th>
    <td><%= @user.user_id %></td>
  </tr>

  <tr class="table-no-l-pad">
    <th class="table-no-l-pad">Name</th>
    <td><%= @user.user_name %></td>
  </tr>

  <tr class="table-no-l-pad">
    <th class="table-no-l-pad">User Role</th>
    <td><%= @user.user_role %></td>
  </tr>
</table>

app/views/users/_user_edit_header_nav.html.erb
<div class="container">
  <div class="row">
    <div class="col col-padding-kill">
      <h3 class="h3-site"><%= title %></h3>
    </div>
    <div class="col col-padding-kill txt-align-right">
      <%= link_to "Back", user_path, class: "btn btn-primary custom-btn" %>
    </div>
  </div>
</div>

app/views/users/_user_list.html.erb
<div class="container table-responsive">
  <% if user_signed_in? %>
    <% if current_user.user_role == "Coordinator" || current_user.user_role == "Manager" %>
      <table class="table table-borderless table-hover">
        <tbody  class="">
        <tr>
          <th class="table-borderless">User ID</th>
          <th>Name</th>
          <th>Specialisation</th>
          <th>Role</th>
          <th>Status</th>
          <th>Batch</th>
          <th>Action</th>
        </tr>

        <% users.each do |user| %>
          <tr>
            <td><%= user.user_id %></td>
            <td><%= user.user_name %></td>
            <td><%= user.student_specialisation %></td>
            <td><%= user.user_role %></td>
            <td><%= user.user_status %></td>
            <td><%= user.student_batch %></td>
            <td><%= link_to "View", user, class: "btn btn-primary custom-btn custom-btn-edit" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <p><%= errmsg_no_permission_to_access %></p>
    <% end %>
  <% else %>
    <p><%= errmsg_no_permission_to_access %></p>
  <% end %>
</div>

app/views/users/edit.html.erb
<div>
  <p><%= link_to "<- Back", user_path %></p>
</div>

<div>
  <span>This is a placeholder page.</span>
</div>

app/views/users/edit_moderator_assign.html.erb
<div class="container container-page">

  <%= render "user_edit_header_nav", title: "Edit User" %>

  <div class="container-contents">
    <div class="container">
      <% if user_signed_in? %>
        <% if current_user.user_role == "Coordinator" %>
          <h5 class="h3-site">Assign Moderator</h5>
          <%= form_with model: @user do |form| %>
            <%= render "user-details-summary" %>

            <% # Store the previous role into `user_role_original` column. %>
            <% if @user.user_role != "Moderator" %>
              <%= form.hidden_field :user_role_original, value: @user.user_role, readonly: true %>
            <% else %>
              <%= form.hidden_field :user_role_original, value: "-", readonly: true %>
            <% end %>

            <div class="row mb-3">
              <div class="col">
                <label class="col col-form-label"><%= r_as %>User Role</label>
                <% if @user.user_role != "Moderator" %>
                  <%= form.select :user_role, [@user.user_role, "Moderator"], {}, class: "form-select" %>
                <% else %>
                  <%= form.select :user_role, [@user.user_role_original, "Moderator"], {}, class: "form-select" %>
                <% end %>
                <% @user.errors.full_messages_for(:user_role).each do |message| %>
                  <div class="txt-red"><%= message %></div>
                <% end %>
              </div>
            </div>

            <div class="row mb-3">
              <div class="col txt-align-right">
                <%= form.submit "Update", class: "btn btn-primary custom-btn"%>
              </div>
            </div>

          <% end %>

        <% else %>
          <p><%= errmsg_no_permission_to_access %></p>
        <% end %>
      <% else %>
        <p><%= errmsg_no_permission_to_access %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit_stud_spec_batch.html.erb
<div class="container container-page">

  <%= render "user_edit_header_nav", title: "Edit User" %>

  <div class="container-contents">
    <div class="container">
      <% if user_signed_in? %>
        <% if current_user.user_role == "Manager" %>
          <h5 class="h3-site">Update Batch/Specialisation</h5>
          <%= form_with model: @user do |form| %>
            <%= render "user-details-summary" %>

            <div class="row mb-3">
              <div class="col">
                <label class="col col-form-label">Batch</label>
                <%= form.select :batch_id, batch_options, {}, class: "form-select" %>
                <% @user.errors.full_messages_for(:batch_id).each do |message| %>
                  <div class="txt-red"><%= message %></div>
                <% end %>
              </div>

              <div class="col">
                <label class="col col-form-label">Specialisation</label>
                <%= form.select :student_specialisation, specialisation_options, {}, class: "form-select" %>
                <% @user.errors.full_messages_for(:student_specialisation).each do |message| %>
                  <div class="txt-red"><%= message %></div>
                <% end %>
              </div>
            </div>

            <div class="row mb-3">
              <div class="col txt-align-right">
                <%= form.submit "Update", class: "btn btn-primary custom-btn" %>
              </div>
            </div>
          <% end %>

        <% else %>
          <p><%= errmsg_no_permission_to_access %></p>
        <% end %>
      <% else %>
        <p><%= errmsg_no_permission_to_access %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit_stud_status.html.erb
<div class="container container-page">

  <%= render "user_edit_header_nav", title: "Edit User" %>

  <div class="container-contents">
    <div class="container">
      <% if user_signed_in? %>
        <% if current_user.user_role == "Manager" %>
          <h5 class="h3-site">Update Student Status</h5>
          <%= form_with model: @user do |form| %>
            <%= render "user-details-summary" %>

            <div class="row mb-3">
              <label class="col col-form-label">Student Status</label>
              <%= form.select :student_status, student_status_options, {}, class: "form-select" %>
              <% @user.errors.full_messages_for(:student_status).each do |message| %>
                <div class="txt-red"><%= message %></div>
              <% end %>
            </div>

            <div class="row mb-3">
              <div class="col txt-align-right">
                <%= form.submit "Update", class: "btn btn-primary custom-btn" %>
              </div>
            </div>

          <% end %>

        <% else %>
          <p><%= errmsg_no_permission_to_access %></p>
        <% end %>
      <% else %>
        <p><%= errmsg_no_permission_to_access %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit_supervisor_assign.html.erb
<div class="container container-page">

  <%= render "user_edit_header_nav", title: "Edit User" %>

  <div class="container-contents">
    <div class="container">

      <% if user_signed_in? %>
        <% if current_user.user_role == "Manager" %>
          <h5 class="h3-site">Assign Supervisor</h5>
          <%= form_with model: @user do |form| %>
            <%= render "user-details-summary" %>
            <br>

            <div class="row mb-3">
              <div class="col">
                <label class="col col-form-label">Is Supervisor?</label>
                <%= form.select :is_supervisor, yes_no_options, {}, class: "form-select" %>
                <% @user.errors.full_messages_for(:is_supervisor).each do |message| %>
                  <div class="txt-red"><%= message %></div>
                <% end %>
              </div>
            </div>

            <div class="row mb-3">
              <div class="col txt-align-right">
                <%= form.submit "Update", class: "btn btn-primary custom-btn" %>
              </div>
            </div>
          <% end %>

        <% else %>
          <p><%= errmsg_no_permission_to_access %></p>
        <% end %>
      <% else %>
        <p><%= errmsg_no_permission_to_access %></p>
      <% end %>

    </div>
  </div>
</div>

app/views/users/edit_user_role_status.html.erb
<div class="container container-page">

  <%= render "user_edit_header_nav", title: "Edit User" %>

  <div class="container-contents">
    <div class="container">

      <% if user_signed_in? %>
        <% if current_user.user_role == "Manager" %>
          <h5 class="h3-site">Edit Role/Status</h5>
          <%= form_with model: @user do |form| %>

            <%= render "user-details-summary" %>

            <div class="row mb-3">
              <span><i>These settings affects the user's access in this portal - please choose carefully!</i></span><br>
            </div>

            <div class="row mb-3">
              <div class="col">
                <label class="col col-form-label"><%= r_as %>User Role</label>
                <%= form.select :user_role, user_role_options, {}, class: "form-select" %>
                <% @user.errors.full_messages_for(:user_role).each do |message| %>
                  <div class="txt-red"><%= message %></div>
                <% end %>
              </div>

              <div class="col">
                <label class="col col-form-label"><%= r_as %>User Status</label>
                <%= form.select :user_status, user_status_options, {}, class: "form-select" %>
                <% @user.errors.full_messages_for(:user_status).each do |message| %>
                  <div class="txt-red"><%= message %></div>
                <% end %>
              </div>
            </div>

            <div class="row mb-3">
              <div class="col txt-align-right">
                <%= form.submit "Update", class: "btn btn-primary custom-btn" %>
              </div>
            </div>

          <% end %>
        <% else %>
          <p><%= errmsg_no_permission_to_access %></p>
        <% end %>
      <% else %>
        <p><%= errmsg_no_permission_to_access %></p>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<style>
    #all {visibility: visible; display: unset;}
    #student {visibility: hidden; display: none;}
    #supervisor {visibility: hidden; display: none;}
    #moderator {visibility: hidden; display: none;}
</style>

<script type="text/javascript">
    function showHide(elementId) {
        let el = document.getElementById(elementId);

        if (el.style.visibility === "hidden") {
            el.style.visibility = "visible";
        } else if (el.style.visibility === "visible") {
            el.style.visibility = "hidden";
        }
    }

    function toggle(elementId) {
        const list = ["all", "student", "supervisor", "moderator"];

        let el_tog = document.getElementById(elementId);
        let el_tog_tab = document.getElementById(elementId + "_tab");  // Tab fx
        el_tog.style.visibility = "visible";
        el_tog.style.display = "unset";
        el_tog_tab.classList.add("active");  // Tab fx
        el_tog_tab.classList.add("tab-bg");  // Tab fx
        console.log(el_tog);

        for (let i = 0; i < list.length; i++) {
            if (list[i] !== elementId) {
                let el_left = document.getElementById(list[i]);
                let el_left_tab = document.getElementById(list[i] + "_tab");  // Tab fx
                el_left.style.visibility = "hidden";
                el_left.style.display = "none";
                el_left_tab.classList.remove("active");  // Tab fx
                el_left_tab.classList.remove("tab-bg");  // Tab fx
            }
        }
    }
</script>

<div class="container container-page">

  <div class="container">
    <div class="row">
      <div class="col col-padding-kill">
        <h3 class="h3-site">User Management</h3>
      </div>
    </div>
  </div>

  <div class="container-contents">

    <div class="container">
      <%= form_tag "/usermgmt", method: :get do %>
        <div class="row sm-3">
          <div class="col">
            <label for="colFormLabel" class="col-form-label">Search Keyword</label>
          </div>
        </div>

        <div class="row mb-4">
          <div class="col">
            <%= text_field_tag :search_keyword, params[:search_keyword], class: "form-control" %>
          </div>
          <div class="col">
            <%= submit_tag "Search", class: "btn btn-primary custom-btn" %>
          </div>
        </div>
      <% end %>
      <hr>
    </div>

    <div>
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <a id="all_tab" class="nav-link tab-font active tab-bg" aria-current="page" onclick="toggle('all')">All</a>
        </li>
        <li class="nav-item">
          <a id="student_tab" class="nav-link tab-font" onclick="toggle('student')">Student</a>
        </li>
        <li class="nav-item">
          <a id="supervisor_tab" class="nav-link tab-font" onclick="toggle('supervisor')">Supervisor</a>
        </li>
        <li class="nav-item">
          <a id="moderator_tab" class="nav-link tab-font" tabindex="-1" onclick="toggle('moderator')">Moderator</a>
        </li>
      </ul>
    </div>

    <%# LIST RENDER %>
    <div id="all" class="container"><%= render "user_list", users: @users %></div>
    <div id="student" class="container"><%= render "user_list", users: @user_student %></div>
    <div id="supervisor" class="container"><%= render "user_list", users: @user_supervisor %></div>
    <div id="moderator" class="container"><%= render "user_list", users: @user_moderator %></div>
  </div>

</div>

<!--<div>-->
<!--  <table>-->
<!--    <tr>-->
<!--      <td><input type=button onClick="toggle('all')" value="All" /></td>-->
<!--      <td><input type=button onClick="toggle('student')" value="Student" /></td>-->
<!--      <td><input type=button onClick="toggle('supervisor')" value="Supervisor" /></td>-->
<!--      <td><input type=button onClick="toggle('moderator')" value="Moderator" /></td>-->
<!--    </tr>-->
<!--  </table>-->
<!--  <br>-->
<!--</div>-->

<!--<div>-->
<%#= form_tag "/usermgmt", method: :get do %>
<!--    <span>Search Keyword: </span>-->
<%#= text_field_tag :search_keyword, params[:search_keyword] %>
<%#= submit_tag "Search" %>
<%# end %>
<!--  <br>-->
<!--</div>-->

app/views/users/show.html.erb
<div class="container container-page">

  <div class="container">
    <div class="row">
      <div class="col col-padding-kill">
        <h3 class="h3-site">View User</h3>
      </div>
      <div class="col col-padding-kill txt-align-right">
        <%= link_to "Back", usermgmt_path, class: "btn btn-primary custom-btn" %>
      </div>
    </div>
  </div>

  <div class="container-contents">
    <div class="container">

      <% if user_signed_in? %>
        <% if current_user.user_role == "Coordinator" || current_user.user_role == "Manager" %>

          <h5 class="h3-site">User Info</h5>
          <table class="table table-borderless table-sm">

            <tr>
              <th class="col-3 table-no-l-pad">User ID</th>
              <td style="font-weight: bold;"><%= @user.user_id %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">User Role</th>
              <td><%= @user.user_role %></td>
            </tr>

            <% if @user.user_role != "Student" %>
              <tr>
                <th class="table-no-l-pad">Additional Role</th>
                <td><%= @user_is_supervisor %></td>
              </tr>
            <% end %>

            <tr>
              <th class="table-no-l-pad">Name</th>
              <td><%= @user.user_name %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">User Status</th>
              <td><%= @user.user_status %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Gender</th>
              <td><%= user_gender_options.each{|k,v| break k if v.include?(User.find(params[:user_id]).user_gender) } %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Gov. ID No.</th>
              <td><%= @user.user_gov_id %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Email Address</th>
              <td><%= @user.email %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Contact Number</th>
              <td><%= @user.user_contact_no %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">User Remarks</th>
              <td><%= @user_user_remarks %></td>
              <%# "gsub(/\n/, '<br/>').html_safe" %>
            </tr>

            <tr>
              <td class="table-no-l-pad">
                <% if current_user.user_role == "Coordinator" && current_user.user_id != @user.user_id %>
                  <%= link_to "Assign Moderator", edit_moderator_assign_path %>
                <% end %>

                <% if current_user.user_role == "Manager" && @user.user_role != "Student" %>
                  <%= link_to "Assign Supervisor", edit_supervisor_assign_path %>
                <% end %>

                <% if current_user.user_role == "Manager" && current_user.user_id != @user.user_id %>
                  <br>
                  <%= link_to "Edit Role/Status", edit_user_role_status_path %>
                <% end %>
              </td>
            </tr>
          </table>

          <% if @user.user_role == "Student" %>
            <hr>
            <%# ---------------------------------------------------- %>

            <h5 class="h3-site">Student Info</h5>
            <table class="table table-borderless table-sm">

              <tr>
                <th class="col-3 table-no-l-pad">Batch</th>
                <td><%= @batch_name %></td>
              </tr>

              <tr>
                <th class="table-no-l-pad">Batch Status</th>
                <td><%= @batch_status %></td>
              </tr>

              <tr>
                <th class="table-no-l-pad">Specialisation</th>
                <td><%= @user.student_specialisation %></td>
              </tr>

              <tr>
                <th class="table-no-l-pad">Student Status</th>
                <td><%= @user.student_status %></td>
              </tr>

              <tr>
                <th class="table-no-l-pad">Project Progress ID</th>
                <td><%= @user.placement_id %></td>
              </tr>

              <% if current_user.user_role == "Manager" %>
                <tr>
                  <td class="table-no-l-pad">
                    <%= link_to "Update Batch/Specialisation", edit_stud_spec_batch_path %>
                    <%= link_to "Update Student Status", edit_stud_status_path %>
                  </td>
                </tr>
              <% end %>

            </table>
          <% end %>



        <% else %>
          <p><%= errmsg_no_permission_to_access %></p>
        <% end %>
      <% else %>
        <p><%= errmsg_no_permission_to_access %></p>
      <% end %>
    </div>
  </div>
</div>