config/routes.rb
Rails.application.routes.draw do
  # get 'presentation_slots/index'
  # get 'presentation_params/index'
  get 'users/index'
  devise_for :users, :skip => [:registrations], :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' },
             path: '', path_names: { sign_in: 'login', sign_up: 'signup', sign_out: 'logout' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "articles#index"
  root to: "home#index"

  get "/announcements", to: "announcements#index"
  get "/announcements/new", to: "announcements#new"
  # These routes goes last whenever possible to avoid `new` controllers getting override.
  get "/announcements/:announcement_id", to: "announcements#show"
  get "/announcements/:announcement_id/edit", to: "announcements#edit"

  get "/projects", to: "projects#index"
  get "/projects/new", to: "projects#new"
  get "/projects/:project_id", to: "projects#show"
  get "/projects/:project_id/edit", to: "projects#edit"
  get "/projects/:project_id/edit_review", to: "projects#edit_review", as: :edit_review
  get "/projects/:project_id/edit_personnel", to: "projects#edit_personnel", as: :edit_personnel
  get "/projects/:project_id/edit_details", to: "projects#edit_details", as: :edit_details
  get "/projects/:project_id/edit_industry_collab", to: "projects#edit_industry_collab", as: :edit_industry_collab

  get "/usermgmt", to: "users#index"
  get "/usermgmt/:user_id", to: "users#show"
  get "/usermgmt/:user_id/edit", to: "users#edit"
  get "/usermgmt/:user_id/edit_stud_spec_batch", to: "users#edit_stud_spec_batch", as: :edit_stud_spec_batch
  get "/usermgmt/:user_id/edit_stud_status", to: "users#edit_stud_status", as: :edit_stud_status
  get "/usermgmt/:user_id/edit_moderator_assign", to: "users#edit_moderator_assign", as: :edit_moderator_assign
  get "/usermgmt/:user_id/edit_supervisor_assign", to: "users#edit_supervisor_assign", as: :edit_supervisor_assign
  get "/usermgmt/:user_id/edit_user_role_status", to: "users#edit_user_role_status", as: :edit_user_role_status

  get "/batchmgmt", to: "batches#index"
  get "/batchmgmt/new", to: "batches#new"
  get "/batchmgmt/:batch_id", to: "batches#show"
  get "/batchmgmt/:batch_id/edit", to: "batches#edit"

  get "/presentations", to: "presentation_slots#index"

  get "/presparams", to: "presentation_params#index"
  get "/presparams/new", to: "presentation_params#new"
  get "/presparams/:params_id", to: "presentation_params#show"
  get "/presparams/:params_id/edit", to: "presentation_params#edit"

  get "/presslots", to: "presentation_slots#index"
  get "/presslots/new", to: "presentation_slots#new"
  get "/presslots/:presentation_id", to: "presentation_slots#show"
  get "/presslots/:presentation_id/edit", to: "presentation_slots#edit"

  get "/projplacements/:placement_id/edit", to: "project_placements#edit"

  get "/stats", to: "stats#index"

  resources :announcements, param: :announcement_id
  resources :projects, param: :project_id
  resources :users, param: :user_id
  resources :batches, param: :batch_id
  resources :presentation_params, param: :param_id
  resources :presentation_slots, param: :presentation_id
  resources :project_placements, param: :placement_id

end

app/models/project.rb
class Project < ApplicationRecord
  scope :projects_confirmed, ->{ where(project_approval_status: "Confirmed") }

  validates :project_id, presence: true, uniqueness: true
  validates :project_title, presence: true, uniqueness: true
  validates :supervisor_id, presence: true
  # validates :co_supervisor_id
  validates :project_type, presence: true
  validates :placement_id, presence: true

  # stud-info
  # TEMPORARILY HIDDEN DUE TO THE NO STUDENT VALIDATION CONSTRAINT.
  # validates :student_one_user_id, length: { minimum: 6, maximum: 10 }
  # validates :student_two_user_id, length: { minimum: 6, maximum: 10 }

  # industry-collab
  validates :is_industry_collab, length: { is: 1 }
  validates :industry_collab_company, length: { maximum: 64 }
  validates :industry_collab_contact_name, length: { maximum: 50 }
  validates :industry_collab_contact_number, length: { maximum: 20 }

  # proj-details-main
  validates :project_description, length: { maximum: 4096 }, presence: true
  validates :project_objective, length: { maximum: 4096 }, presence: true
  validates :project_scope, length: { maximum: 4096 }, presence: true

  after_validation :log_errors, :if => Proc.new{ |m| m.errors }
  def log_errors
    Rails.logger.debug self.errors.full_messages.join("\n\n")
  end

  belongs_to :user, class_name: "User", foreign_key: :supervisor_id, optional: true

  has_one :project_placement
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    if user_signed_in?
      curr_usr_role = current_user.user_role    # The role of current user.

      if curr_usr_role == "Manager" || curr_usr_role == "Coordinator"
        if curr_usr_role == "Coordinator"
          @projects = Project.all.order(created_at: :asc)
        else
          @projects = Project.projects_confirmed.order(created_at: :asc)
        end

        @users = User.all

        # IF THE SEARCH BOX CONTAINS KEYWORDS
        if params[:search_keyword] && params[:search_keyword] != ""
          # @users = @users.where("user_id like ?", params[:search_by_id])
          # `ilike` is case-insensitive
          @projects = @projects.where('project_id ilike :search OR project_title ilike :search', search: "%#{params[:search_keyword]}%")

          if params[:pending_projects] && params[:confirmed_projects]
            @projects = @projects.where('project_approval_status=\'Pending\' OR project_approval_status=\'Confirmed\'')
          end
          if params[:confirmed_projects] && params[:pending_projects].nil?
            @projects = @projects.where('project_approval_status=\'Confirmed\'')
          end
          if params[:pending_projects] && params[:confirmed_projects].nil?
            @projects = @projects.where('project_approval_status=\'Pending\'')
          end
        end

        # IF THE SEARCH BOX DOES NOT CONTAIN KEYWORDS
        if params[:search_keyword] == ""
          if params[:pending_projects] && params[:confirmed_projects]
            @projects = @projects.where('project_approval_status=\'Pending\' OR project_approval_status=\'Confirmed\'')
          end
          if params[:confirmed_projects] && params[:pending_projects].nil?
            @projects = @projects.where('project_approval_status=\'Confirmed\'')
          end
          if params[:pending_projects] && params[:confirmed_projects].nil?
            @projects = @projects.where('project_approval_status=\'Pending\'')
          end
        end
      end
    end
  end

  def show
    if user_signed_in?
      curr_usr_role = current_user.user_role    # The role of current user.

      if curr_usr_role == "Manager" || curr_usr_role == "Coordinator"
        @project = Project.find(params[:project_id])
        @supervisor = User.find(@project.supervisor_id)

        # Pass the Project ID for project placement module.
        $project_id_pass = @project.project_id

        @created_at = @project.created_at.strftime('%d/%m/%Y %H:%M')
        if @project.created_at != @project.updated_at
          @last_updated = "(Updated at: " + @project.updated_at.strftime('%d/%m/%Y %H:%M') + ")"
        else
          @last_updated = ""
        end

        # ------ Co-supervisor's Name------
        if @project.co_supervisor_id.nil? || @project.co_supervisor_id == "-"
          @co_supervisor = "-"
        else
          @co_supervisor = User.find(@project.co_supervisor_id).user_name
        end


        # ------ Approval's Name ------
        if @project.reviewed_by.nil?
          @reviewed_by = "-"
        else
          @reviewed_by = User.find(@project.reviewed_by).user_name
        end

        # ------ List out other specialisations ------
        @other_specialisation = check_empty_value(@project.project_other_specialisations)


        # ------ Student/Manager Info from `placement_id` ------
        proj_placement = @project.placement_id
        if proj_placement.nil? || proj_placement == "" || proj_placement == "-"
          @student_one_user_name = "-"
          @student_one_subtitle = "-"
          @student_one_work_distribution = "-"
          @student_two_user_name = "-"
          @student_two_subtitle = "-"
          @student_two_work_distribution = "-"
          @moderator = "-"
        else
          placement_stud_raw = User.where(placement_id: proj_placement)
          placement_stud_name = placement_stud_raw.pluck(:user_name)
          placement_stud_uid = placement_stud_raw.pluck(:user_id)

          if placement_stud_raw[0].nil? || placement_stud_raw[0] == "" || placement_stud_raw[0] == "-"
            @student_one_user_name = "-"
          else
            @student_one_user_name = placement_stud_name[0] + " (" + placement_stud_uid[0] + ")"
          end


          if placement_stud_raw[1].nil? || placement_stud_raw[1] == "" || placement_stud_raw[1] == "-"
            @student_two_user_name = "-"
          else
            @student_two_user_name = placement_stud_name[1] + " (" + placement_stud_uid[1] + ")"
          end

          @student_one_subtitle = check_empty_value(@project.student_one_subtitle)
          @student_one_work_distribution = check_empty_value(@project.student_one_work_distribution)
          @student_two_subtitle = check_empty_value(@project.student_two_subtitle)
          @student_two_work_distribution = check_empty_value(@project.student_two_work_distribution)

          moderator_raw = ProjectPlacement.find_by_placement_id(proj_placement).moderator_id
          if moderator_raw.nil? || moderator_raw == "-" || moderator_raw == ""
            @moderator = "-"
          else
            @moderator = User.find_by_user_id(moderator_raw).user_name
          end

          @placement_stat = ProjectPlacement.find_by_placement_id(proj_placement).placement_status
        end

        if @project.is_industry_collab == "Y"
          @industry_collab_company = @project.industry_collab_company
          @industry_collab_contact_name = @project.industry_collab_contact_name
          @industry_collab_contact_number = @project.industry_collab_contact_number
        else
          @industry_collab_company = "-"
          @industry_collab_contact_name = "-"
          @industry_collab_contact_number = "-"
        end
      end
    end
  end

  def new
    if user_signed_in?
      curr_usr_role = current_user.user_role
      if curr_usr_role == "Manager" || curr_usr_role == "Coordinator"
        @project = Project.new
        @batches = Batch.pluck(:batch_name, :batch_id)
        @supervisors = User.where(:user_role =>  "Coordinator").pluck(:user_name, :user_id)
        @current_uid = current_user.user_id
        @button_text = "Create"
      end
    end
  end

  def create
    if user_signed_in?
      curr_usr_role = current_user.user_role
      if curr_usr_role == "Manager" || curr_usr_role == "Coordinator"
        @project = Project.new(project_params)

        @passed_project_id = @project.project_id.to_s
        @passed_batch_id = @project.batch_id.to_s
        @project.placement_id = @passed_project_id

        @project_placement = ProjectPlacement.new(
          :placement_id => @passed_project_id, :project_id => @passed_project_id,
          :placement_batch => @passed_batch_id, :placement_status => "Inactive",
          :moderator_id => "-", :presentation_id => "-"
        )

        if @project.save && @project_placement.save
          redirect_to @project
        else
          @project.errors.each {|err| puts err }
          puts "[DEBUG] Error is #{@project.errors.to_s}"
          render :new, status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @project = Project.find(params[:project_id])
  end

  def update
    if user_signed_in?
      curr_usr_role = current_user.user_role
      if curr_usr_role == "Manager" || curr_usr_role == "Coordinator"
        @project = Project.find(params[:project_id])

        if @project.update(project_params)
          redirect_to @project
        else
          render :edit, status: :unprocessable_entity
        end
      end
    end
  end

  def edit_review
    @project = Project.find(params[:project_id])
  end

  def edit_personnel
    @project = Project.find(params[:project_id])
  end

  def edit_details
    @project = Project.find(params[:project_id])
  end

  def edit_industry_collab
    @project = Project.find(params[:project_id])
  end

  # Return dash if column is empty (only applicable for direct data retrieval)
  private
  def check_empty_value(target)
    if target == "" || target.nil? || target == "-"
      "-"
    else
      target
    end
  end

  private
  def project_params
    params.require(:project).permit(
      :project_title, :project_id, :project_title, :project_approval_status, :project_proposal_party,    #5
      :project_type, :project_category, :project_focus, :project_date, :project_other_specialisations,     #5
      :project_description, :project_objective, :project_scope, :project_status, :project_specialisation,     #5
      :project_background, :project_outcomes, :project_doc_id, :supervisor_id, :co_supervisor_id, :moderator_id,    #6
      :reviewed_by, :student_one_user_id, :student_one_subtitle, :student_one_work_distribution, :student_two_user_id,    #5
      :student_two_subtitle, :student_two_work_distribution, :is_industry_collab, :industry_collab_company,    #4
      :batch_id, :remarks_project, :remarks_supervisor, :industry_collab_contact_name, :industry_collab_contact_number,    #5
      :placement_id, :passed_project_id
    )
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  def batch_options
    b = Batch.pluck(:batch_name, :batch_id)
    return b
  end

  def co_supervisor_options
    cs = User.where(:user_role => %w[Coordinator Manager Moderator Supervisor]).pluck(:user_name, :user_id).append(["-"])
    return cs
  end

  def supervisor_options
    sp = User.where(:user_role =>  %w[Coordinator Manager Moderator Supervisor]).pluck(:user_name, :user_id)
  end
end

app/views/projects/_proj-details-summary.html.erb
<table class="table table-borderless table-sm">
  <tr class="table-no-l-pad">
    <th class="col-2 table-no-l-pad">Project ID</th>
    <td><%= @project.project_id %></td>
  </tr>

  <tr class="table-no-l-pad">
    <th class="table-no-l-pad">Project Title</th>
    <td><%= @project.project_title %></td>
  </tr>
</table>

app/views/projects/edit_details.html.erb
<div class="container container-page">

  <div class="container">
    <div class="row">
      <div class="col col-padding-kill">
        <h3 class="h3-site">Edit Project</h3>
      </div>
      <div class="col col-padding-kill txt-align-right">
        <%= link_to "Back", project_path, class: "btn btn-primary custom-btn" %>
      </div>
    </div>
  </div>

  <div class="container-contents">
    <div class="container">

      <% if user_signed_in? %>
        <% if current_user.user_role == "Coordinator" %>

          <h5 class="h3-site">Project Details</h5>
          <%= form_with model: @project do |form| %>

            <%= render "proj-details-summary" %>

            <div class="row mb-3">
              <% # ------ Project Description ----- # %>
              <div class="col">
                <label class="col col-form-label"><%= r_as %>Project Description</label>
                <%= form.text_area :project_description, class: "form-control", rows: 6 %>
                <% @project.errors.full_messages_for(:project_description).each do |message| %>
                  <div class="txt-red"><%= message %></div>
                <% end %>
              </div>
            </div>

            <%# ----------------------------------------------------- %>

            <div class="row mb-3">
              <% # ------ Project Objectives ----- # %>
              <div class="col">
                <label class="col col-form-label"><%= r_as %>Project Objective</label>
                <%= form.text_area :project_objective, class: "form-control", rows: 6 %>
                <% @project.errors.full_messages_for(:project_objective).each do |message| %>
                  <div class="txt-red"><%= message %></div>
                <% end %>
              </div>
            </div>

            <%# ----------------------------------------------------- %>

            <div class="row mb-3">
              <% # ------ Project Scope ----- # %>
              <div class="col">
                <label class="col col-form-label"><%= r_as %>Project Scope</label>
                <%= form.text_area :project_scope, class: "form-control", rows: 6 %>
                <% @project.errors.full_messages_for(:project_scope).each do |message| %>
                  <div class="txt-red"><%= message %></div>
                <% end %>
              </div>
            </div>

            <%# ----------------------------------------------------- %>

            <div class="row mb-3">
              <div class="txt-align-right">
                <%= form.submit "Update", class: "btn btn-primary custom-btn" %>
              </div>
            </div>

          <% end %>
          <% # ------------------------------------------------------------------------------------------ # %>
        <% else %>
          <p><%= errmsg_no_permission_to_access %></p>
        <% end %>
      <% else %>
        <p><%= errmsg_no_permission_to_access %></p>
      <% end %>

    </div>
  </div>
</div>

app/views/projects/edit_review.html.erb
<div class="container container-page">

  <div class="container">
    <div class="row">
      <div class="col col-padding-kill">
        <h3 class="h3-site">Edit Project</h3>
      </div>
      <div class="col col-padding-kill txt-align-right">
        <%= link_to "Back", project_path, class: "btn btn-primary custom-btn" %>
      </div>
    </div>
  </div>

  <div class="container-contents">
    <div class="container">

      <% if user_signed_in? %>
        <% if current_user.user_role == "Coordinator" %>

          <h5 class="h3-site">Project Approval Details</h5>
          <%= form_with model: @project do |form| %>

            <%= render "proj-details-summary" %>
            <br>

            <div class="row mb-3">
              <% # ------ Project Status ----- # %>
              <div class="col">
                <label class="col col-form-label"><%= r_as %>Project Approval Status</label>
                <%= form.select :project_approval_status, project_approval_options, {}, class: "form-select" %>
                <% @project.errors.full_messages_for(:project_approval_status).each do |message| %>
                  <div class="txt-red"><%= message %></div>
                <% end %>
              </div>
            </div>

            <% # ------ Reviewed By (HIDDEN) ----- # %>
            <div>
              <%= form.hidden_field :reviewed_by, value: current_user.user_id, readonly: true %>
            </div>

            <div class="row mb-3">
              <div class="txt-align-right">
                <%= form.submit "Update", class: "btn btn-primary custom-btn" %>
              </div>
            </div>

          <% end %>
          <% # ------------------------------------------------------------------------------------------ # %>
        <% else %>
          <p><%= errmsg_no_permission_to_access %></p>
        <% end %>
      <% else %>
        <p><%= errmsg_no_permission_to_access %></p>
      <% end %>

    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container container-page">

  <div class="container">
    <div class="row">
      <div class="col col-padding-kill">
        <h3 class="h3-site">Projects</h3>
      </div>
      <div class="col col-padding-kill txt-align-right">
        <% if user_signed_in? %>
          <% if current_user.user_role == "Coordinator" %>
            <%= link_to "New", new_project_path, class: "btn btn-primary custom-btn" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container-contents">
    <% if user_signed_in? %>
      <% if current_user.user_role == "Coordinator" || current_user.user_role == "Manager" %>

        <div class="container">
          <%= form_tag "/projects", method: :get do %>
            <div class="row mb-3">
              <div class="col">
                <label class="col col-form-label">Search Keyword</label>
                <%= text_field_tag :search_keyword, params[:search_keyword], class: "form-control" %>
              </div>
            </div>

            <div class="row mb-3">
              <div class="col">
                <div class="form-check">
                  <%= check_box_tag :pending_projects, {}, false, class: "form-check-input" %>
                  <%= label_tag(:pending_projects, "Pending Projects", class: "form-check-label") %>
                </div>
              </div>
              <div class="col">
                <div class="form-check">
                  <%= check_box_tag :confirmed_projects, {}, false, class: "form-check-input" %>
                  <%= label_tag(:confirmed_projects, "Confirmed Projects", class: "form-check-label") %>
                </div>
              </div>
            </div>

            <div class="row mb-3">
              <div class="col txt-align-right">
                <%= link_to 'Reset', projects_path, class: "btn btn-primary custom-btn custom-btn-red" %>
                <%= submit_tag "Search", class: "btn btn-primary custom-btn" %>
              </div>
            </div>
          <% end %>
        </div>

        <hr>

        <div class="container table-responsive">
          <table class="table table-borderless table-hover">
            <tr>
              <th>Project ID</th>
              <th>Project Title</th>
              <th>Lecturer</th>
              <th>Specialisation</th>
              <% if current_user.user_role == "Coordinator" %><th>Approval Status</th><% end %>
              <th>Action</th>
            </tr>

            <% @projects.each do |project| %>
              <% # Find out the name of lecturer/supervisor. Temporary variable. %>
              <% lecturer = @users.find(project.supervisor_id) %>

              <tr>
                <td><%= project.project_id %></td>
                <td><%= project.project_title %></td>

                <% # Check if local variable `lecturer` is empty. %>
                <% unless lecturer.nil? || lecturer == ""  %>
                  <td><%= lecturer.user_name %></td>
                <% else %>
                  <td><%= project.supervisor_id %></td>
                <% end %>

                <td><%= project.project_specialisation %></td>
                <% if current_user.user_role == "Coordinator" %><td><%= project.project_approval_status %></td><% end %>
                <td>
                  <%= link_to "View", project, class: "btn btn-primary custom-btn custom-btn-edit" %>
                  <%# if current_user.user_role == "Coordinator" %>
                  <!--                <span> | <a href="/projects/<%#= project.project_id %>/edit">Edit</a></span>-->
                  <%# end %>
                </td>
              </tr>
            <% end %>

          </table>
        </div>

      <% else %>
        <p><%= errmsg_no_permission_to_access %></p>
      <% end %>
    <% else %>
      <p><%= errmsg_no_permission_to_access %></p>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container container-page">

  <div class="container">
    <div class="row">
      <div class="col col-padding-kill">
        <h3 class="h3-site">View Project</h3>
      </div>
      <div class="col col-padding-kill txt-align-right">
        <%= link_to "Back", projects_path, class: "btn btn-primary custom-btn" %>
      </div>
    </div>
  </div>

  <div class="container-contents">
    <div class="container">

      <% if user_signed_in? %>
        <% if current_user.user_role == "Coordinator" || current_user.user_role == "Manager" %>

          <!--          <div class="row">-->
          <!--            <div class="col">-->
          <!--              <h5 class="h3-site"><%#= @project.project_title %></h5>-->
          <!--            </div>-->
          <!--          </div>-->

          <h5 class="h3-site">Project Overview</h5>
          <table class="table table-borderless table-sm">
            <tr>
              <th class="col-3 table-no-l-pad">Project ID</th>
              <td style="font-weight: bold;"><%= @project.project_id %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Project Title</th>
              <td><%= @project.project_title %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Project Status</th>
              <td><%= @project.project_status %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Project Batch</th>
              <td><%= batch_options.each{|k,v| break k if v.include?(Project.find(params[:project_id]).batch_id) } %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Project Type</th>
              <td><%= project_type_options.each{|k,v| break k if v.include?(Project.find(params[:project_id]).project_type) } %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Specialisation</th>
              <td><%= @project.project_specialisation %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Project Category</th>
              <td><%= @project.project_category %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Focus</th>
              <td><%= @project.project_focus %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Other Specialisation</th>
              <td><%= @other_specialisation %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Created On</th>
              <td>
                <%= @created_at %> <i><%= @last_updated %></i>
              </td>
            </tr>

            <% if current_user.user_role == "Coordinator" %>
              <tr>
                <td class="col-2 table-no-l-pad">
                  <%= link_to "Edit", edit_project_path %>
                </td>
              </tr>
            <% end %>

          </table>

          <hr>
          <%# ---------------------------------------------------- %>

          <h5 class="h3-site">Personnel Details</h5>
          <table class="table table-borderless table-sm">

            <tr>
              <th class="col-3 table-no-l-pad">Supervisor</th>
              <td><%= @supervisor.user_name %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Co-supervisor</th>
              <td><%= @co_supervisor %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Moderator</th>
              <td><%= @moderator %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Student 1 Name</th>
              <td><%= @student_one_user_name %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Student 1 Subtitle</th>
              <td><%= @student_one_subtitle %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Student 1 Work Distribution</th>
              <td><%= @student_one_work_distribution %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Student 2 Name</th>
              <td><%= @student_two_user_name %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Student 2 Subtitle</th>
              <td><%= @student_two_subtitle %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Student 2 Work Distribution</th>
              <td><%= @student_two_work_distribution %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Placement Status</th>
              <td><%= @placement_stat %></td>
            </tr>

            <% if current_user.user_role == "Coordinator" %>
              <tr>
                <td class="table-no-l-pad">
                  <%=link_to "Edit Placement", edit_project_placement_path(@project.placement_id) %>
                  <br>
                  <%= link_to "Edit Details", edit_personnel_path %>
                </td>
              </tr>
            <% end %>

          </table>

          <hr>
          <%# ---------------------------------------------------- %>

          <h5 class="h3-site">Project Approval Details</h5>
          <table class="table table-borderless table-sm">

            <tr>
              <th class="col-3 table-no-l-pad">Approval Status</th>
              <td><%= @project.project_approval_status %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Approved by</th>
              <td><%= @reviewed_by %></td>
            </tr>

            <% if current_user.user_role == "Coordinator" %>
              <tr>
                <td class="table-no-l-pad">
                  <%= link_to "Review", edit_review_path %>
                </td>
              </tr>
            <% end %>

          </table>

          <hr>
          <%# ---------------------------------------------------- %>

          <h5 class="h3-site">Project Details</h5>
          <table class="table table-borderless table-sm">

            <tr>
              <th class="col-3 table-no-l-pad">Project Description</th>
              <td><%= @project.project_description.gsub(/\n/, '<br/>').html_safe %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Project Objective</th>
              <td><%= @project.project_objective.gsub(/\n/, '<br/>').html_safe %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Project Scope</th>
              <td><%= @project.project_scope.gsub(/\n/, '<br/>').html_safe %></td>
            </tr>

            <% if current_user.user_role == "Coordinator" %>
              <tr>
                <td class="table-no-l-pad">
                  <%= link_to "Edit", edit_details_path %>
                </td>
              </tr>
            <% end %>

          </table>

          <hr>
          <%# ---------------------------------------------------- %>

          <h5 class="h3-site">Industry Collaboration Details</h5>
          <table class="table table-borderless table-sm">

            <tr>
              <th class="col-3 table-no-l-pad">Industry Collaboration</th>
              <td><%= yes_no_options.each{|k,v| break k if v.include?(Project.find(params[:project_id]).is_industry_collab) } %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Company</th>
              <td><%= @industry_collab_company %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Contact Name</th>
              <td><%= @industry_collab_contact_name %></td>
            </tr>

            <tr>
              <th class="table-no-l-pad">Contact Number</th>
              <td><%= @industry_collab_contact_number %></td>
            </tr>

            <% if current_user.user_role == "Coordinator" %>
              <tr>
                <td class="table-no-l-pad">
                  <%= link_to "Edit", edit_industry_collab_path %>
                </td>
              </tr>
            <% end %>

          </table>

        <% else %>
          <p><%= errmsg_no_permission_to_access %></p>
        <% end %>
      <% else %>
        <p><%= errmsg_no_permission_to_access %></p>
      <% end %>

    </div>
  </div>
</div>