config/routes.rb
Rails.application.routes.draw do
  # get 'presentation_slots/index'
  # get 'presentation_params/index'
  get 'users/index'
  devise_for :users, :skip => [:registrations], :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' },
             path: '', path_names: { sign_in: 'login', sign_up: 'signup', sign_out: 'logout' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "articles#index"
  root to: "home#index"

  get "/announcements", to: "announcements#index"
  get "/announcements/new", to: "announcements#new"
  # These routes goes last whenever possible to avoid `new` controllers getting override.
  get "/announcements/:announcement_id", to: "announcements#show"
  get "/announcements/:announcement_id/edit", to: "announcements#edit"

  get "/projects", to: "projects#index"
  get "/projects/new", to: "projects#new"
  get "/projects/:project_id", to: "projects#show"
  get "/projects/:project_id/edit", to: "projects#edit"
  get "/projects/:project_id/edit_review", to: "projects#edit_review", as: :edit_review
  get "/projects/:project_id/edit_personnel", to: "projects#edit_personnel", as: :edit_personnel
  get "/projects/:project_id/edit_details", to: "projects#edit_details", as: :edit_details
  get "/projects/:project_id/edit_industry_collab", to: "projects#edit_industry_collab", as: :edit_industry_collab

  get "/usermgmt", to: "users#index"
  get "/usermgmt/:user_id", to: "users#show"
  get "/usermgmt/:user_id/edit", to: "users#edit"
  get "/usermgmt/:user_id/edit_stud_spec_batch", to: "users#edit_stud_spec_batch", as: :edit_stud_spec_batch
  get "/usermgmt/:user_id/edit_stud_status", to: "users#edit_stud_status", as: :edit_stud_status
  get "/usermgmt/:user_id/edit_moderator_assign", to: "users#edit_moderator_assign", as: :edit_moderator_assign
  get "/usermgmt/:user_id/edit_supervisor_assign", to: "users#edit_supervisor_assign", as: :edit_supervisor_assign
  get "/usermgmt/:user_id/edit_user_role_status", to: "users#edit_user_role_status", as: :edit_user_role_status

  get "/batchmgmt", to: "batches#index"
  get "/batchmgmt/new", to: "batches#new"
  get "/batchmgmt/:batch_id", to: "batches#show"
  get "/batchmgmt/:batch_id/edit", to: "batches#edit"

  get "/presentations", to: "presentation_slots#index"

  get "/presparams", to: "presentation_params#index"
  get "/presparams/new", to: "presentation_params#new"
  get "/presparams/:params_id", to: "presentation_params#show"
  get "/presparams/:params_id/edit", to: "presentation_params#edit"

  get "/presslots", to: "presentation_slots#index"
  get "/presslots/new", to: "presentation_slots#new"
  get "/presslots/:presentation_id", to: "presentation_slots#show"
  get "/presslots/:presentation_id/edit", to: "presentation_slots#edit"

  get "/projplacements/:placement_id/edit", to: "project_placements#edit"

  get "/stats", to: "stats#index"

  resources :announcements, param: :announcement_id
  resources :projects, param: :project_id
  resources :users, param: :user_id
  resources :batches, param: :batch_id
  resources :presentation_params, param: :param_id
  resources :presentation_slots, param: :presentation_id
  resources :project_placements, param: :placement_id

end

app/models/presentation_slot.rb
class PresentationSlot < ApplicationRecord
  validates :presentation_id, presence: true, uniqueness: true
  # validates :user_id, length: { minimum: 6, maximum: 10 }, presence: true, uniqueness: true
  # validates :presentation_location, length: { maximum: 32 }
  # validates :presentation_type, length: { is: 3 }
  # validates :supervisor_id, length: { minimum: 6, maximum: 10 }
  # validates :moderator_id, length: { minimum: 6, maximum: 10 }
  # validates :co_supervisor_id, length: { minimum: 6, maximum: 10 }
  # validates :project_id
  validates :other_attendees, length: { maximum: 512 }
  validates :presentation_remarks, length: { maximum: 2048 }
  # validates :presentation_score, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
end

app/controllers/presentation_slots_controller.rb
class PresentationSlotsController < ApplicationController

  # ------ TEMP ------
  # before_action :pres_params_dropdown
  #
  def index
    curr_usr_role = current_user.user_role    # The role of current user.

    if curr_usr_role == "Manager" || curr_usr_role == "Coordinator"
      @pres_slots = PresentationSlot.all.order(presentation_id: :desc)
    end
  end

  def show
    curr_usr_role = current_user.user_role    # The role of current user.

    if curr_usr_role == "Manager" || curr_usr_role == "Coordinator"
      @pres_slot = PresentationSlot.find(params[:presentation_id])
      # @pres_param_venues = @pres_param.presentation_venue.tr('[]\" ', '').split(/,+/)
      # @pres_param_slots = @pres_param.presentation_time_slots.tr('[]\"', '').split(/,+/)

      @project = Project.find_by_project_id(ProjectPlacement.find_by_placement_id(@pres_slot.placement_id).project_id)
      @project_id = @project.project_id
      @project_title = @project.project_title
      # @project_title = Project.find_by_project_id(@pres_slot.project_id).project_title
      # @stud1_name = User.find_by_user_id(@pres_slot.student_one_id).user_name

      # STUDENT 2 NAME
      # ctrl_std_two = User.find_by_user_id(@pres_slot.student_two_id)
      # if ctrl_std_two == "-" || ctrl_std_two == nil
      #   @stud2_name = "-"
      # else
      #   @stud2_name = ctrl_std_two.user_name
      # end

      placement_stud_raw = User.where(placement_id: @pres_slot.placement_id)
      placement_stud_name = placement_stud_raw.pluck(:user_name)
      placement_stud_uid = placement_stud_raw.pluck(:user_id)
      stud1_name = placement_stud_name[0]
      stud1_id = placement_stud_uid[0]
      @stud1_info = stud1_name + " (" + stud1_id + ")"
      if placement_stud_raw[1].nil? || placement_stud_raw[1] == ""
        @stud2_info = "-"
      else
        stud2_name = placement_stud_name[1]
        stud2_id = placement_stud_uid[1]
        @stud2_info = stud2_name + " (" + stud2_id + ")"
      end

      # # SUPERVISOR NAME
      # ctrl_pres_spvsr = User.find_by_user_id(@pres_slot.supervisor_id)
      ctrl_pres_spvsr = User.find_by_user_id(@project.supervisor_id)
      if ctrl_pres_spvsr == "-" || ctrl_pres_spvsr == nil
        @supervisor_name = "-"
      else
        @supervisor_name = ctrl_pres_spvsr.user_name
      end

      # CO-SUPERVISOR NAME
      ctrl_pres_co_spvsr = User.find_by_user_id(@project.co_supervisor_id)
      if ctrl_pres_co_spvsr == "-" || ctrl_pres_co_spvsr == nil
        @co_supervisor_name = "-"
      else
        @co_supervisor_name = ctrl_pres_co_spvsr.user_name
      end

      # MODERATOR NAME
      ctrl_pres_moderator = User.find_by_user_id(ProjectPlacement.find(@pres_slot.placement_id).moderator_id)
      if ctrl_pres_moderator == "-" || ctrl_pres_moderator == nil
        @moderator_name = "-"
      else
        @moderator_name = ctrl_pres_moderator.user_name
      end

      ctrl_pres_other_attd = @pres_slot.other_attendees
      if ctrl_pres_other_attd == "" || ctrl_pres_other_attd == nil
        @pres_other_attendees = "-"
      else
        @pres_other_attendees = ctrl_pres_other_attd
      end

      ctrl_pres_remarks = @pres_slot.presentation_remarks
      if ctrl_pres_remarks == "" || ctrl_pres_remarks == nil
        @pres_remarks = "-"
      else
        @pres_remarks = ctrl_pres_remarks
      end

      param_raw = PresentationParam.find_by_param_id(@pres_slot.param_id)
      @param_name = param_raw.param_name

      if param_raw.presentation_type == "INT"
        @param_type = "Interim"
      elsif param_raw.presentation_type == "POS"
        @param_type = "Poster"
      else
        @param_type = "-"
      end
    end
  end

  def new
    @pres_slot = PresentationSlot.new

    # ------ TEMP ------
    # @presparams = PresentationParam.all
    # @presparams_timeslots = @presparam&.presentation_time_slots || []
  end

  def create
    curr_usr_role = current_user.user_role    # The role of current user.

    if curr_usr_role == "Manager"
      @pres_slot = PresentationSlot.new(pres_slot_params)

      @proj_placement = ProjectPlacement.find_by_placement_id(pres_slot_params[:placement_id])
      @proj_placement.update(:presentation_id => pres_slot_params[:presentation_id])

      if @pres_slot.save
        redirect_to @pres_slot
      else
        @pres_slot.errors.each {|err| puts err }
        puts "[DEBUG] Error is #{@pres_slot.errors.full_messages}"
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit
    @pres_slot = PresentationSlot.find(params[:presentation_id])
  end

  def update
    curr_usr_role = current_user.user_role    # The role of current user.

    if curr_usr_role == "Manager"
      @pres_slot = PresentationSlot.find(params[:presentation_id])

      if @pres_slot.update(pres_slot_params)
        redirect_to @pres_slot
      else
        @pres_slot.errors.each {|err| puts err }
        puts "[DEBUG] Error is #{@pres_slot.errors.full_messages}"
        render :edit, status: :unprocessable_entity
      end
    end
  end

  private
  def pres_slot_params
    params.require(:presentation_slot).permit(
      :presentation_id, :presentation_location, :supervisor_id, :co_supervisor_id, :moderator_id,
      :project_id, :other_attendees, :presentation_remarks, :presentation_score, :presentation_date,
      :presentation_time, :student_one_id, :param_id, :placement_id
    )
  end

  # ------ TEMP ------
  # private
  # def pres_params_dropdown
  #   @presparam = PresentationParam.find_by(param_id: params[:param_name].presence)
  #   @presparams_timeslots = PresentationParam.find_by(param_id: params[:presentation_time_slots].presence)
  # end
end

app/helpers/presentation_slots_helper.rb
module PresentationSlotsHelper
  def param_options
    b = PresentationParam.pluck(:param_name, :param_id)
  end

  def placement_options
    p = ProjectPlacement.where(:placement_status => "Active").pluck(:project_id, :placement_id)
  end
end

app/views/presentation_slots/_form.html.erb
<%= form_with model: pres_slot do |form| %>

  <div class="row mb-3">
    <div class="col">
      <label class="col col-form-label"><%= r_as %>Presentation ID</label>
      <div class="form-text">Format: PSxxxx (e.g. "PS0004")</div>
      <% if action == "C" %>
        <%= form.text_field :presentation_id, class: "form-control", maxlength: 6 %>
      <% else %>
        <%= form.text_field :presentation_id, class: "form-control", maxlength: 6, readonly: true, style: "background-color:#EEEEEE" %>
      <% end %>
      <% pres_slot.errors.full_messages_for(:presentation_id).each do |message| %>
        <div class="txt-red"><%= message %></div>
      <% end %>
    </div>

    <div class="col">
      <label class="col col-form-label"><%= r_as %>Project ID</label>
      <div class="form-text">Change of Project is no longer allowed after slot creation.</div>
      <% if action == "C" %>
        <%= form.select :placement_id, placement_options, {}, class: "form-select" %>
      <% else %>
        <%= form.select :placement_id, placement_options, {}, class: "form-select", disabled: true %>
        <%= form.hidden_field :placement_id, value: pres_slot.placement_id, readonly: true %>
      <% end %>
      <% pres_slot.errors.full_messages_for(:placement_id).each do |message| %>
        <div class="txt-red"><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col">
      <label class="col col-form-label"><%= r_as %>Date</label>
      <%= form.date_field :presentation_date, class: "form-control" %>
      <% pres_slot.errors.full_messages_for(:presentation_date).each do |message| %>
        <div class="txt-red"><%= message %></div>
      <% end %>
    </div>

    <div class="col">
      <label class="col col-form-label"><%= r_as %>Time</label>
      <%= form.select :presentation_time, presentation_time_slot_options, {}, class: "form-select" %>
      <% pres_slot.errors.full_messages_for(:presentation_time).each do |message| %>
        <div class="txt-red"><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col">
      <label class="col col-form-label"><%= r_as %>Location</label>
      <%= form.select :presentation_location, presentation_venue_options, {}, class: "form-select" %>
      <% pres_slot.errors.full_messages_for(:presentation_location).each do |message| %>
        <div class="txt-red"><%= message %></div>
      <% end %>
    </div>

    <div class="col">
      <label class="col col-form-label"><%= r_as %>Presentation Parameters</label>
      <!--      <div class="form-text">Format: PSxxxx (e.g. "PS0004")</div>-->
      <%= form.select :param_id, param_options, {}, class: "form-select" %>
      <% pres_slot.errors.full_messages_for(:param_id).each do |message| %>
        <div class="txt-red"><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col">
      <label class="col col-form-label">Other Attendees</label>
      <%= form.text_area :other_attendees, class: "form-control", rows: 3 %>
      <% pres_slot.errors.full_messages_for(:other_attendees).each do |message| %>
        <div class="txt-red"><%= message %></div>
      <% end %>
    </div>

  </div>

  <div class="row mb-3">
    <div class="col">
      <label class="col col-form-label">Presentation Remarks</label>
      <%= form.text_area :presentation_remarks, class: "form-control", rows: 3 %>
      <% pres_slot.errors.full_messages_for(:presentation_remarks).each do |message| %>
        <div class="txt-red"><%= message %></div>
      <% end %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col txt-align-right">
      <%= form.submit button_text, class: "btn btn-primary custom-btn" %>
    </div>
  </div>
<% end %>

app/views/presentation_slots/edit.html.erb
<div class="container container-page">

  <div class="container">
    <div class="row">
      <div class="col col-padding-kill">
        <h3 class="h3-site">Edit Presentation Slot</h3>
      </div>
      <div class="col col-padding-kill txt-align-right">
        <%= link_to "Back", presentation_slot_path, class: "btn btn-primary custom-btn" %>
      </div>
    </div>
  </div>

  <div class="container-contents">
    <div class="container">
      <% if user_signed_in? %>
        <% if current_user.user_role == "Manager" %>
          <div>
            <%= render "form", pres_slot: @pres_slot, action: "U", button_text: "Update" %>
          </div>
        <% else %>
          <p><%= errmsg_no_permission_to_access %></p>
        <% end %>
      <% else %>
        <p><%= errmsg_no_permission_to_access %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/presentation_slots/index.html.erb
<div class="container container-page">

  <div class="container">
    <div class="row">
      <div class="col col-padding-kill">
        <h3 class="h3-site">Presentation Slots</h3>
      </div>
      <% if user_signed_in? %>
        <% if current_user.user_role == "Manager" %>
          <div class="col col-padding-kill txt-align-right">
            <%= link_to "New", new_presentation_slot_path, class: "btn btn-primary custom-btn" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="container-contents">
    <div class="container table-responsive">
      <% if user_signed_in? %>
        <% if current_user.user_role == "Manager" || current_user.user_role == "Coordinator" %>

          <% if current_user.user_role == "Manager" %>
            <div class="row">
              <div class="col col-padding-kill txt-align-right">
                <span><%= link_to "Presentation Parameters Setup", presentation_params_path %></span>
              </div>
            </div>
          <% end %>

          <table class="table table-borderless table-hover">
            <tr>
              <th>Presentation ID</th>
              <th>Project ID</th>
              <th>Date/Time</th>
              <th>Student Name(s)</th>
              <th>Supervisor(s)</th>
              <th>Moderator</th>
              <th>Location</th>
              <th>Action</th>
            </tr>

            <% @pres_slots.each do |slot| %>
              <% moderator = ProjectPlacement.where(placement_id: slot.placement_id) %>
              <% placement_stud_raw = User.where(placement_id: slot.placement_id) %>
              <% placement_stud_name = placement_stud_raw.pluck(:user_name) %>
              <% stud1_name = placement_stud_name[0] %>
              <% if placement_stud_raw[1].nil? || placement_stud_raw[1] == "" || placement_stud_raw[1] == "-" %>
                <%  stud2_name = "" %>
              <% else %>
                <%  stud2_name = " & " + placement_stud_name[1] %>
              <% end %>
              <% placement_supervisor_raw = Project.where(placement_id: slot.placement_id) %>
              <% placement_supervisor_name = placement_supervisor_raw.pluck(:supervisor_id)[0] %>
              <% supervisor1_name = User.find_by_user_id(placement_supervisor_name).user_name %>
              <% project_title_render = placement_supervisor_raw.pluck(:project_id)[0] %>
              <% if placement_supervisor_raw.pluck(:supervisor_id)[1].nil? || placement_supervisor_raw.pluck(:supervisor_id)[1] == "-" || placement_supervisor_raw.pluck(:supervisor_id)[1] == "" %>
                <% supervisor2_name = "" %>
              <% else %>
                <% supervisor2_name = " & " + User.find_by_user_id(placement_supervisor_raw.pluck(:supervisor_id)[1]).user_name %>
              <% end %>
              <% moderator_raw = moderator.pluck(:moderator_id)[0] %>
              <% if moderator_raw.nil? || moderator_raw == "" || moderator_raw == "-" %>
                <% mod_name_display = "-" %>
              <% else %>
                <% mod_name_display = User.find_by_user_id(moderator_raw).user_name %>
              <% end %>

              <tr>
                <td><%= slot.presentation_id %></td>
                <td><%= project_title_render %></td>
                <td><%= slot.presentation_date.strftime('%d/%m/%Y') + " " + slot.presentation_time %></td>
                <td><%= stud1_name + stud2_name %></td>
                <td><%= supervisor1_name + supervisor2_name %></td>
                <td><%= mod_name_display %></td>
                <td><%= slot.presentation_location %></td>
                <td><%= link_to "View", slot, class: "btn btn-primary custom-btn custom-btn-edit" %></td>
              </tr>
            <% end %>
          </table>

        <% else %>
          <p><%= errmsg_no_permission_to_access %></p>
        <% end %>
      <% else %>
        <p><%= errmsg_no_permission_to_access %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/presentation_slots/new.html.erb
<div class="container container-page">

  <div class="container">
    <div class="row">
      <div class="col col-padding-kill">
        <h3 class="h3-site">New Presentation Slot</h3>
      </div>
      <div class="col col-padding-kill txt-align-right">
        <%= link_to "Back", presentation_slots_path, class: "btn btn-primary custom-btn" %>
      </div>
    </div>
  </div>

  <div class="container-contents">
    <div class="container">
      <% if user_signed_in? %>
        <% if current_user.user_role == "Manager" %>
          <div>
            <%= render "form", pres_slot: @pres_slot, action: "C", button_text: "Create" %>
          </div>
        <% else %>
          <p><%= errmsg_no_permission_to_access %></p>
        <% end %>
      <% else %>
        <p><%= errmsg_no_permission_to_access %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/presentation_slots/show.html.erb
<div class="container container-page">
  <div class="container">
    <div class="row">
      <div class="col col-padding-kill">
        <h3 class="h3-site">Presentation Slot</h3>
      </div>
      <div class="col col-adding-kill txt-align-right">
        <p><%= link_to "Back", presentation_slots_path, class: "btn btn-primary custom-btn" %></p>
      </div>
    </div>
  </div>

  <div class="container-contents">
    <div class="container">
      <% if user_signed_in? %>
        <% if current_user.user_role == "Manager" || current_user.user_role == "Coordinator" %>

          <table class="table table-borderless table-sm">
            <tr>
              <th class="col-3 table-no-l-pad">Presentation ID</th>
              <td style="font-weight: bold"><%= @pres_slot.presentation_id %></td>
            </tr>

            <tr>
              <th class="col-3 table-no-l-pad">Date/Time</th>
              <td><%= @pres_slot.presentation_date.strftime('%d/%m/%Y') + " " + @pres_slot.presentation_time %></td>
            </tr>

            <tr>
              <th class="col-3 table-no-l-pad">Presentation Parameter</th>
              <td><%= @param_name %></td>
            </tr>

            <tr>
              <th class="col-3 table-no-l-pad">Presentation Type</th>
              <td><%= @param_type %></td>
            </tr>

            <tr>
              <th class="col-3 table-no-l-pad">Location</th>
              <td><%= @pres_slot.presentation_location %></td>
            </tr>

            <tr>
              <th class="col-3 table-no-l-pad">Project ID</th>
              <td><%= @project_id %></td>
            </tr>

            <tr>
              <th class="col-3 table-no-l-pad">Project Title</th>
              <td><%= @project_title %></td>
            </tr>

            <tr>
              <th class="col-3 table-no-l-pad">Remarks</th>
              <td><%= @pres_remarks.gsub(/\n/, '<br/>').html_safe %></td>
            </tr>
          </table>

          <hr>

          <table class="table table-borderless table-sm">
            <tr>
              <th class="col-3 table-no-l-pad">Student 1</th>
              <td><%= @stud1_info %></td>
            </tr>

            <tr>
              <th class="col-3 table-no-l-pad">Student 2</th>
              <td><%= @stud2_info %></td>
            </tr>

            <tr>
              <th class="col-3 table-no-l-pad">Supervisor</th>
              <td><%= @supervisor_name %></td>
            </tr>

            <tr>
              <th class="col-3 table-no-l-pad">Co-Supervisor</th>
              <td><%= @co_supervisor_name %></td>
            </tr>

            <tr>
              <th class="col-3 table-no-l-pad">Moderator</th>
              <td><%= @moderator_name %></td>
            </tr>

            <tr>
              <th class="col-3 table-no-l-pad">Other Attendees</th>
              <td><%= @pres_other_attendees.gsub(/\n/, '<br/>').html_safe %></td>
            </tr>

            <% if current_user.user_role == "Manager" %>
              <tr>
                <td class="table-no-l-pad"><%= link_to "Edit", edit_presentation_slot_path(@pres_slot) %></td>
              </tr>
            <% end %>
          </table>

        <% else %>
          <p><%= errmsg_no_permission_to_access %></p>
        <% end %>
      <% else %>
        <p><%= errmsg_no_permission_to_access %></p>
      <% end %>
    </div>
  </div>

</div>