config/routes.rb
Rails.application.routes.draw do
  # get 'presentation_slots/index'
  # get 'presentation_params/index'
  get 'users/index'
  devise_for :users, :skip => [:registrations], :controllers => { registrations: 'users/registrations', sessions: 'users/sessions' },
             path: '', path_names: { sign_in: 'login', sign_up: 'signup', sign_out: 'logout' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "articles#index"
  root to: "home#index"

  get "/announcements", to: "announcements#index"
  get "/announcements/new", to: "announcements#new"
  # These routes goes last whenever possible to avoid `new` controllers getting override.
  get "/announcements/:announcement_id", to: "announcements#show"
  get "/announcements/:announcement_id/edit", to: "announcements#edit"

  get "/projects", to: "projects#index"
  get "/projects/new", to: "projects#new"
  get "/projects/:project_id", to: "projects#show"
  get "/projects/:project_id/edit", to: "projects#edit"
  get "/projects/:project_id/edit_review", to: "projects#edit_review", as: :edit_review
  get "/projects/:project_id/edit_personnel", to: "projects#edit_personnel", as: :edit_personnel
  get "/projects/:project_id/edit_details", to: "projects#edit_details", as: :edit_details
  get "/projects/:project_id/edit_industry_collab", to: "projects#edit_industry_collab", as: :edit_industry_collab

  get "/usermgmt", to: "users#index"
  get "/usermgmt/:user_id", to: "users#show"
  get "/usermgmt/:user_id/edit", to: "users#edit"
  get "/usermgmt/:user_id/edit_stud_spec_batch", to: "users#edit_stud_spec_batch", as: :edit_stud_spec_batch
  get "/usermgmt/:user_id/edit_stud_status", to: "users#edit_stud_status", as: :edit_stud_status
  get "/usermgmt/:user_id/edit_moderator_assign", to: "users#edit_moderator_assign", as: :edit_moderator_assign
  get "/usermgmt/:user_id/edit_supervisor_assign", to: "users#edit_supervisor_assign", as: :edit_supervisor_assign
  get "/usermgmt/:user_id/edit_user_role_status", to: "users#edit_user_role_status", as: :edit_user_role_status

  get "/batchmgmt", to: "batches#index"
  get "/batchmgmt/new", to: "batches#new"
  get "/batchmgmt/:batch_id", to: "batches#show"
  get "/batchmgmt/:batch_id/edit", to: "batches#edit"

  get "/presentations", to: "presentation_slots#index"

  get "/presparams", to: "presentation_params#index"
  get "/presparams/new", to: "presentation_params#new"
  get "/presparams/:params_id", to: "presentation_params#show"
  get "/presparams/:params_id/edit", to: "presentation_params#edit"

  get "/presslots", to: "presentation_slots#index"
  get "/presslots/new", to: "presentation_slots#new"
  get "/presslots/:presentation_id", to: "presentation_slots#show"
  get "/presslots/:presentation_id/edit", to: "presentation_slots#edit"

  get "/projplacements/:placement_id/edit", to: "project_placements#edit"

  get "/stats", to: "stats#index"

  resources :announcements, param: :announcement_id
  resources :projects, param: :project_id
  resources :users, param: :user_id
  resources :batches, param: :batch_id
  resources :presentation_params, param: :param_id
  resources :presentation_slots, param: :presentation_id
  resources :project_placements, param: :placement_id

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MMU FCI FYP Portal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <style>
    .navbar-custom { background-color: #274C77; }
    .navbar-text-white { color: white; }
  </style>

  <body class="body-bg">
    <nav class="navbar navbar-expand-lg navbar-custom d-print">
      <div class="container-fluid">
        <a class="navbar-brand navbar-text-white" href="/"><b>MMU FCI FYP PORTAL</b></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

            <% if user_signed_in? %>
              <%# # SHARED: MANAGER, COORDINATOR %>
              <% if current_user.user_role == "Manager" || current_user.user_role == "Coordinator" %>
                <li class="nav-item"><%= link_to "User Management", usermgmt_path, class: "nav-link navbar-text-white" %></li>
                <li class="nav-item"><%= link_to "Projects", projects_path, class: "nav-link navbar-text-white" %></li>
                <li class="nav-item"><%= link_to "Presentations", presentations_path, class: "nav-link navbar-text-white" %></li>
                <li class="nav-item"><%= link_to "Announcements", announcements_path, class: "nav-link navbar-text-white" %></li>
              <% end %>

              <%# # EXCLUSIVE: MANAGER %>
              <% if current_user.user_role == "Manager" %>
                <li class="nav-item"><%= link_to "Batch Management", batchmgmt_path, class: "nav-link navbar-text-white" %></li>
              <% end %>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle navbar-text-white" href="#"
                   role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= current_user.user_name %>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                  <li class="dropdown-item disabled">
                    <%= current_user.user_name %><br>
                    <span class="nav-username-role">
                      <%= current_user.user_role %> (<%= current_user.user_id %>)
                    </span>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                  <li><%= link_to "FYP Statistics", stats_path, class: "dropdown-item" %></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete },
                        class: "dropdown-item" %></li>
                </ul>
              </li>

            <% else %>
  <!--            <li><%##= link_to "Sign Up" , new_user_registration_path %></li>-->
              <li><%= link_to "Log In", new_user_session_path, class: "nav-link navbar-text-white", data: { turbo: false } %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

<!--    <p class="notice"><%#= notice %></p>-->
<!--    <p class="alert"><%#= alert %></p>-->
    <%= yield %>
  </body>
</html>